title: Code and Wave
description: Just Code and Wave coders. Just Code and Wave.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "http://www.codeandwave.com/" # change this to the base hostname & protocol for your site
permalink: /:categories/:title
# permalink: /
markdown: kramdown
theme: # leave it empty

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-email-protect


email: "nelzkie.coder@gmail.com"

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"




  




# social
author: "Nelzkie"
image: /thumbnail-jumbo.png
twitter:
  username: CodeandWave
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:

google_plus:
 url: https://plus.google.com/106969025067298354254
 username: Code And Wave



paginate: 7
paginate_path: "/blog/page:num/"