title: Code and Wave
description: Just Code and Wave coders. Just Code and Wave.
show_downloads: true

baseurl: "/CodeAndWave" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "" # change this to the base hostname & protocol for your site
permalink: /:categories/:title
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Nelzkie"
image: /thumbnail-jumbo.png
twitter:
  username: NelzkieCoder
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
